sudo: false
language: node_js
node_js: 8
cache:
  directories:
    - ~/.npm
before_install:
  - npm install -g http-server
install:
  - npm install
  - cd demo/03-submachines
  - npm install
  - cp -r ../../build ./node_modules/machinate/
before_script:
  - npm run build
  - http-server ./build -p 3001 &
  - cd ../..
script:
  - npm test
  - $(npm bin)/cypress run --record