sudo: false
language: node_js
node_js: 8
cache:
  directories:
    - ~/.npm
before_install:
  - npm install -g http-server
install:
  - npm link
  - cd demo/03-submachines && npm install
  - npm link machinate
  - npm run build
  - http-server ./build -p 3001 &
  - cd ../..
script:
  - npm test
  - $(npm bin)/cypress run --record
after_failure:
  - find /home/travis/.npm/_logs/ -type f -exec cat {} +