sudo: false
language: node_js
node_js: 8
cache:
  directories:
    - ~/.npm
    - node_modules
before_install:
  - npm install -g http-server
install:
  - npm install
  - cd demo-03-submachines && npm install && npm build
  - http-server ./ -p 3001 &
script:
  - npm test
  - $(npm bin)/cypress run --record